development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: project_development
  pool: 5
  username: postgres
  password: admin

test: &TEST
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: project_test
  pool: 5
  username: postgres
  password: admin

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: project_production
  pool: 5
  username: postgres
  password: admin

cucumber:
  <<: *TEST
